# Site settings
language: ""
name: LampApps
description: "Helping the average small business owner to maximize their online presence at the lowest cost. We do this by guiding you through the steps of building a website, choosing an email service, and other low cost (even free) online services that businesses of any size can use."
google-verification: ""
markdown: kramdown
highlighter: rouge
twitter: lampapps
facebook: lampapps
github: lampapps

# Handling Reading
include:
  #- ".htaccess"
  #- "_pages"

exclude:
  #- "/assets/"
  #- "bower.json"
  #- "composer.json"
  #- "composer.lock"
  #- "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  #- "/gulp/"
  #- "gulpfile.js"
  #- "LICENSE.md"
  #- "Makefile"
  #- "node_modules"
  #- "npm-debug.log"
  #- "package.json"
  - "README.md"
  #- "rev-manifest.json"
  - "s3_website.yml"

# Plugins
gems: [jekyll-paginate, sass, jekyll-feed, jekyll-sitemap]

# Conversion
#incremental:      true

# Serving
url: http://www.lampapps.com
# baseurl:  "" # does not include hostname

# keep_files: 
#   - css/pure.css

sass:
  style: compressed

# Outputting
excerpt_separator: <!--more-->
permalink: /:year/:month/:day/:title.html
paginate: 3
paginate_path: "blog/page:num"

timezone: America/New_York

